

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    invalid_annotation_target: ignore
  exclude:
    - '**.freezed.dart'
    - '**.mocks.dart'
    - '**.g.dart'
    - '**/generated_plugin_registrant.dart'
    - 'lib/di/injection_container.config.dart'
linter:
  rules:
    sort_pub_dependencies: false
